-- Shock
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+5% [COLOR_POSITIVE_TEXT]側翼加成[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_1_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+5% [COLOR_POSITIVE_TEXT]側翼加成[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_2_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+5% [COLOR_POSITIVE_TEXT]側翼加成[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SHOCK_3_HELP';

-- Drill
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]-15% 來自城市的傷害.'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_1_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]-15% 來自城市的傷害.'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_2_HELP';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]-15% 來自城市的傷害.'
WHERE Tag = 'TXT_KEY_PROMOTION_DRILL_3_HELP';

-- Barrage
UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_1_HELP';

UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_2_HELP';

UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_BARRAGE_3_HELP';

-- Accuracy
UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]不超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_1_HELP';

UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]不超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_2_HELP';

UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]不超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_ACCURACY_3_HELP';

-- Targeting
UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]海軍[ENDCOLOR]和[COLOR_POSITIVE_TEXT]陸地單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]不超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_1_HELP';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]海軍[ENDCOLOR]和[COLOR_POSITIVE_TEXT]陸地單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]不超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_2_HELP';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]海軍[ENDCOLOR]和[COLOR_POSITIVE_TEXT]陸地單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]不超過 50% HP 的單位[ENDCOLOR]時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_TARGETING_3_HELP';

-- Sentry
UPDATE Language_en_US
SET Text = '+1 [ICON_VP_VISION]視野.'
WHERE Tag = 'TXT_KEY_PROMOTION_SENTRY_HELP';

UPDATE Language_en_US
SET Text = '孤注一擲'
WHERE Tag = 'TXT_KEY_PROMOTION_SIEGE';

UPDATE Language_en_US
SET Text = '-10% [ICON_STRENGTH]戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +100% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_SIEGE_HELP';

-- Volley
UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]駐紮單位[ENDCOLOR]和[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +50% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_VOLLEY_HELP';

-- Medic
UPDATE Language_en_US
SET Text = '醫療 I'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]治療[ENDCOLOR]時, 若單位[COLOR_POSITIVE_TEXT]在這個單元格上或相鄰[ENDCOLOR] +5 HP.'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_HELP';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]治療[ENDCOLOR]時, 若單位[COLOR_POSITIVE_TEXT]在這個單元格上或相鄰[ENDCOLOR] +5 HP.[NEWLINE]治療時, 若在[COLOR_POSITIVE_TEXT]友好領土外[ENDCOLOR] +5 HP.'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_II_HELP';

-- Amphibious
UPDATE Language_en_US
SET Text = '消除從海上或渡河攻擊的戰鬥懲罰.[NEWLINE]渡河只消耗 1 [ICON_MOVES]移動力.[NEWLINE]忽略[COLOR_POSITIVE_TEXT]湿地[ENDCOLOR]的地形成本.'
WHERE Tag = 'TXT_KEY_PROMOTION_AMPHIBIOUS_HELP';

-- Cover
UPDATE Language_en_US
SET Text = '防禦[COLOR_POSITIVE_TEXT]遠程攻擊[ENDCOLOR]時 +25% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_COVER_1_HELP';

UPDATE Language_en_US
SET Text = '防禦[COLOR_POSITIVE_TEXT]遠程攻擊[ENDCOLOR]時 +25% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_COVER_2_HELP';

UPDATE Language_en_US
SET Text = '猛烈衝鋒 I'
WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE';

UPDATE Language_en_US
SET Text = '在[COLOR_POSITIVE_TEXT]開闊地形[ENDCOLOR]攻擊單位時 +10% [ICON_STRENGTH]戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]受傷單位[ENDCOLOR]時 +20% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_CHARGE_HELP';

-- Formation
UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH]戰鬥力 VS [COLOR_POSITIVE_TEXT]騎乘單位[ENDCOLOR].[NEWLINE]在[COLOR_POSITIVE_TEXT]開闊地形[ENDCOLOR]防禦時 +15% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_1_HELP';

UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH]戰鬥力 VS [COLOR_POSITIVE_TEXT]騎乘單位[ENDCOLOR].[NEWLINE]在[COLOR_POSITIVE_TEXT]開闊地形[ENDCOLOR]防禦時 +15% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_FORMATION_2_HELP';

-- Ambush
UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH]戰鬥力 VS [COLOR_POSITIVE_TEXT]裝甲單位[ENDCOLOR].[NEWLINE]在[COLOR_POSITIVE_TEXT]崎嶇地形[ENDCOLOR]攻擊單位時 +15% [ICON_STRENGTH]戰鬥力.[NEWLINE][NEWLINE]一旦你完成研究 [COLOR_CYAN]{TXT_KEY_TECH_COMBUSTION_TITLE}[ENDCOLOR] 即可用.'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_1_HELP';

UPDATE Language_en_US
SET Text = '+33% [ICON_STRENGTH]戰鬥力 VS [COLOR_POSITIVE_TEXT]裝甲單位[ENDCOLOR].[NEWLINE]在[COLOR_POSITIVE_TEXT]崎嶇地形[ENDCOLOR]攻擊單位時 +15% [ICON_STRENGTH]戰鬥力.[NEWLINE][NEWLINE]一旦你完成研究 [COLOR_CYAN]{TXT_KEY_TECH_COMBUSTION_TITLE}[ENDCOLOR] 即可用.'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBUSH_2_HELP';

-- Supply
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]友好領土外[ENDCOLOR]可以治療.[NEWLINE][COLOR_POSITIVE_TEXT]治療[ENDCOLOR]時 +5 HP.'
WHERE Tag = 'TXT_KEY_PROMOTION_SUPPLY_HELP';

-- March
UPDATE Language_en_US
SET Text = '單位會[COLOR_POSITIVE_TEXT]每回合自我治療[ENDCOLOR], 即使執行了行動.'
WHERE Tag = 'TXT_KEY_PROMOTION_MARCH_HELP';

-- Blitz
UPDATE Language_en_US
SET Text = '+1 [ICON_WAR]攻擊.[NEWLINE]攻擊後可移動.'
WHERE Tag = 'TXT_KEY_PROMOTION_BLITZ_HELP';

-- Woodsman
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]崎嶇地形[ENDCOLOR] +10% [ICON_STRENGTH]戰鬥力.[NEWLINE]忽略[COLOR_POSITIVE_TEXT]森林[ENDCOLOR]和[COLOR_POSITIVE_TEXT]叢林[ENDCOLOR]的地形成本.'
WHERE Tag = 'TXT_KEY_PROMOTION_WOODSMAN_HELP';

-- Logistics
UPDATE Language_en_US
SET Text = '+1 [ICON_WAR]攻擊.[NEWLINE]攻擊時 -30% [ICON_RANGE_STRENGTH]遠程戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_LOGISTICS_HELP';

-- Range
UPDATE Language_en_US
SET Text = '+1 [ICON_RANGE_STRENGTH]範圍.[NEWLINE]攻擊時 -20% [ICON_RANGE_STRENGTH]遠程戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_RANGE_HELP';

-- Mobility, Mobility I, Mobility II
UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES]移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_MOBILITY_HELP';

UPDATE Language_en_US
SET Text = '王牌飛行員 I'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1';

UPDATE Language_en_US
SET Text = '+33% 機率可以[COLOR_POSITIVE_TEXT]攔截[ENDCOLOR]敵人空中單位.'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_1_HELP';

UPDATE Language_en_US
SET Text = '王牌飛行員 II'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2';

UPDATE Language_en_US
SET Text = '+33% 機率可以[COLOR_POSITIVE_TEXT]攔截[ENDCOLOR]敵人空中單位.[NEWLINE][COLOR_POSITIVE_TEXT]攔截[ENDCOLOR]敵人空中單位時 +33% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_2_HELP';

UPDATE Language_en_US
SET Text = '王牌飛行員 III'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3';

UPDATE Language_en_US
SET Text = '+34% 機率可以[COLOR_POSITIVE_TEXT]攔截[ENDCOLOR]敵人空中單位.[NEWLINE][COLOR_POSITIVE_TEXT]攔截[ENDCOLOR]敵人空中單位時 +33% [ICON_STRENGTH]戰鬥力.[NEWLINE]+1 作業範圍.'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_3_HELP';

UPDATE Language_en_US
SET Text = '王牌飛行員 IV'
WHERE Tag = 'TXT_KEY_PROMOTION_SORTIE';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]攔截[ENDCOLOR]敵人空中單位時 +34% [ICON_STRENGTH]戰鬥力.[NEWLINE]+1 作業範圍.[NEWLINE]+1 [COLOR_POSITIVE_TEXT]攔截次數[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SORTIE_HELP';

-- Dogfighting
UPDATE Language_en_US
SET Text = '執行[COLOR_POSITIVE_TEXT]空中掃蕩[ENDCOLOR]時 +33% [ICON_STRENGTH]戰鬥力. 如果本次空中掃蕩[COLOR_POSITIVE_TEXT]沒有被攔截[ENDCOLOR], 造成 5 傷害給在目標單元格上或相鄰的所有[COLOR_POSITIVE_TEXT]空中單位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP';

UPDATE Language_en_US
SET Text = '執行[COLOR_POSITIVE_TEXT]空中掃蕩[ENDCOLOR]時 +33% [ICON_STRENGTH]戰鬥力. 如果本次空中掃蕩[COLOR_POSITIVE_TEXT]沒有被攔截[ENDCOLOR], 造成 10 傷害給在目標單元格上或相鄰的所有[COLOR_POSITIVE_TEXT]空中單位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP';

UPDATE Language_en_US
SET Text = '執行[COLOR_POSITIVE_TEXT]空中掃蕩[ENDCOLOR]時 +34% [ICON_STRENGTH]戰鬥力. 如果本次空中掃蕩[COLOR_POSITIVE_TEXT]沒有被攔截[ENDCOLOR], 造成 15 傷害給在目標單元格上或相鄰的所有[COLOR_POSITIVE_TEXT]空中單位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP';

-- Siege (Air)
UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +50% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +50% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +50% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP';

-- Bombardment
UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +30% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP';

UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +30% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP';

UPDATE Language_en_US
SET Text = '攻擊時 +10% [ICON_RANGE_STRENGTH]遠程戰鬥力.[NEWLINE]攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +30% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP';

UPDATE Language_en_US
SET Text = '定位 I'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1';

UPDATE Language_en_US
SET Text = '定位 II'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_2';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]海軍[ENDCOLOR]和[COLOR_POSITIVE_TEXT]陸地單位[ENDCOLOR]時 +15% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP';

-- Air Ambush I, Air Ambush II
UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH]戰鬥力 VS [COLOR_POSITIVE_TEXT]裝甲單位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP';

UPDATE Language_en_US
SET Text = '規避能力'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION';

UPDATE Language_en_US
SET Text = '執行[COLOR_POSITIVE_TEXT]空襲[ENDCOLOR]時, -50% 收到的傷害.'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_HELP';

-- Scouting
UPDATE Language_en_US
SET Text = '+1 [ICON_VP_VISION]視野和海運視野.'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_1_HELP';

UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES]移動力和海運移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_SCOUTING_2_HELP';

-- Survivalism
UPDATE Language_en_US
SET Text = '防禦時 +25% [ICON_STRENGTH]戰鬥力.[NEWLINE]治療時, 若在[COLOR_POSITIVE_TEXT]友好領土外[ENDCOLOR] +5 HP.'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_1_HELP';

UPDATE Language_en_US
SET Text = '防禦時 +25% [ICON_STRENGTH]戰鬥力.[NEWLINE]治療時, 若在[COLOR_POSITIVE_TEXT]友好領土外[ENDCOLOR] +5 HP.'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_2_HELP';

UPDATE Language_en_US
SET Text = '單位會[COLOR_POSITIVE_TEXT]每回合自我治療[ENDCOLOR], 即使執行了行動.[NEWLINE]掠奪不會消耗[ICON_MOVES]移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_SURVIVALISM_3_HELP';

UPDATE Language_en_US
SET Text = '坦克獵手 I'
WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_1';

UPDATE Language_en_US
SET Text = '坦克獵手 II'
WHERE Tag = 'TXT_KEY_PROMOTION_HELI_AMBUSH_2';

UPDATE Language_en_US
SET Text = '船殼 I'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+10 生命點.'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP';

UPDATE Language_en_US
SET Text = '船殼 II'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+15 生命點.'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP';

UPDATE Language_en_US
SET Text = '船殼 III'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+15 生命點.'
WHERE Tag = 'TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP';

-- Boarding Party
UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH]戰鬥力.[NEWLINE]敵人海軍單位攻擊或近戰防禦時, 對其造成 [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_BOARDED_1}[ENDCOLOR] 狀態, 減少他們 2 [ICON_MOVES]移動力, 持續 1 回合.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP';

UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH]戰鬥力.[NEWLINE]免疫[COLOR_POSITIVE_TEXT]逆風[ENDCOLOR] 狀態.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP';

UPDATE Language_en_US
SET Text = '+15% [ICON_STRENGTH]戰鬥力.[NEWLINE]敵人海軍單位攻擊或近戰防禦時, 對其造成 [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_BOARDED_2}[ENDCOLOR] 狀態, 減少他們 4 [ICON_MOVES]移動力, 持續 1 回合.'
WHERE Tag = 'TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP';

UPDATE Language_en_US
SET Text = '魚雷 I'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_1';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]海軍[ENDCOLOR]和[COLOR_POSITIVE_TEXT]陸地單位[ENDCOLOR]時 +30% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_1_HELP';

UPDATE Language_en_US
SET Text = '魚雷 II'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_2';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]海軍[ENDCOLOR]和[COLOR_POSITIVE_TEXT]陸地單位[ENDCOLOR]時 +30% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_2_HELP';

UPDATE Language_en_US
SET Text = '魚雷 III'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_3';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]海軍[ENDCOLOR]和[COLOR_POSITIVE_TEXT]陸地單位[ENDCOLOR]時 +30% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_WOLFPACK_3_HELP';

-- Flight Deck
UPDATE Language_en_US
SET Text = '+1 運載槽位.'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_1_HELP';

UPDATE Language_en_US
SET Text = '+1 運載槽位.'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_2_HELP';

UPDATE Language_en_US
SET Text = '+1 運載槽位.'
WHERE Tag = 'TXT_KEY_PROMOTION_FLIGHT_DECK_3_HELP';

-- Armor Plating
UPDATE Language_en_US
SET Text = '防禦時 +25% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_1_HELP';

UPDATE Language_en_US
SET Text = '防禦時 +25% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_2_HELP';

UPDATE Language_en_US
SET Text = '防禦時 +25% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_ARMOR_PLATING_3_HELP';

UPDATE Language_en_US
SET Text = '空中突防 I'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_I';

UPDATE Language_en_US
SET Text = '空中突防 II'
WHERE Tag = 'TXT_KEY_PROMOTION_EVASION_II';

UPDATE Language_en_US
SET Text = '攔截機 I'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_I';

UPDATE Language_en_US
SET Text = '攔截機 II'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_II';

UPDATE Language_en_US
SET Text = '攔截機 III'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_III';

UPDATE Language_en_US
SET Text = '攔截機 IV'
WHERE Tag = 'TXT_KEY_PROMOTION_INTERCEPTION_IV';

UPDATE Language_en_US
SET Text = '空中優勢 I'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR';

UPDATE Language_en_US
SET Text = '空中優勢 II'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_AIR_II';

UPDATE Language_en_US
SET Text = '獵鷹'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_FIGHTER';

-- Buffalo Chest
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+25 生命點.'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_CHEST_HELP';

-- Buffalo Horns
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+25% [COLOR_POSITIVE_TEXT]側翼加成[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_HORNS_HELP';

-- Buffalo Loins
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]+1 [ICON_MOVES]移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_BUFFALO_LOINS_HELP';

-- Embarkation with Ocean移動力
UPDATE Language_en_US
SET Text = '可以在[COLOR_POSITIVE_TEXT]水面單元格[ENDCOLOR]上海運和進入[COLOR_POSITIVE_TEXT]海洋[ENDCOLOR].[NEWLINE]+2 [ICON_VP_VISION]海運視野.'
WHERE Tag = 'TXT_KEY_PROMOTION_ALLWATER_EMBARKATION_HELP';

-- Naval移動力
UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES]移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_MOVEMENT_HELP';

-- Exploration
UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES]移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP';

-- Patriotic War
UPDATE Language_en_US
SET Text = '在[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]中或相鄰 +20% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_NATIONALISM_HELP';

-- Altitude Training
UPDATE Language_en_US
SET Text = '在[COLOR_POSITIVE_TEXT]丘陵[ENDCOLOR]有雙倍[ICON_MOVES]移動力.[NEWLINE]在[COLOR_POSITIVE_TEXT]無特徵丘陵[ENDCOLOR]上防守或攻擊單位時 +10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_ALTITUDE_TRAINING_HELP';

-- Morale 
UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_MORALE_HELP';

-- Statue Of Zeus
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]軍事單位:[ENDCOLOR] 攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +25% [ICON_STRENGTH]戰鬥力.[NEWLINE][COLOR_POSITIVE_TEXT]工人:[ENDCOLOR] 免疫 [COLOR_NEGATIVE_TEXT]{TXT_KEY_PROMOTION_PRISONER_WAR}[ENDCOLOR] 狀態.'
WHERE Tag = 'TXT_KEY_PROMOTION_STATUE_ZEUS_HELP';

-- Himeji Castle
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]友好領土內[ENDCOLOR] +15% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP';

UPDATE Language_en_US
SET Text = '反坦克彈'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_TANK';

UPDATE Language_en_US
SET Text = '攻城懲罰'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_NEGATIVE_TEXT]城市[ENDCOLOR]時 -33% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_PENALTY_HELP';

-- Hovering Unit
UPDATE Language_en_US
SET Text = '可以進入[COLOR_POSITIVE_TEXT]無法通行[ENDCOLOR]單元格, 並且沒有海運也可以進入水面單元格.[NEWLINE]在[COLOR_NEGATIVE_TEXT]海洋[ENDCOLOR]無法攻擊.'
WHERE Tag = 'TXT_KEY_PROMOTION_HOVERING_UNIT_HELP';

UPDATE Language_en_US
SET Text = '所有單元格消耗 1 [ICON_MOVES]移動力.[NEWLINE][COLOR_NEGATIVE_TEXT]不能使用道路和鐵路.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST';

UPDATE Language_en_US
SET Text = '攻城器械'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +100% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_SIEGE_HELP';

-- Indirect Fire
UPDATE Language_en_US
SET Text = '可以越過障礙執行遠程攻擊.[NEWLINE]攻擊時 -10% [ICON_RANGE_STRENGTH]遠程戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP';

-- Extra視野 While海運
UPDATE Language_en_US
SET Text = '+1 [ICON_VP_VISION]海運視野.'
WHERE Tag = 'TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP';

-- Embarkation with Defense
UPDATE Language_en_US
SET Text = '海運時防禦 +100% [ICON_STRENGTH]戰鬥力.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升級時丟失.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP';

-- Skyranger
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]友好領土內[ENDCOLOR]可以[COLOR_POSITIVE_TEXT]空投[ENDCOLOR]最多 40 單元格.'
WHERE Tag = 'TXT_KEY_PROMOTION_EXTENDED_PARADROP_HELP';

UPDATE Language_en_US
SET Text = '海洋風險'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE';

UPDATE Language_en_US
SET Text = '深水炸彈 I'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_I';

UPDATE Language_en_US
SET Text = '深水炸彈 II'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_II';

UPDATE Language_en_US
SET Text = '無聲獵人'
WHERE Tag = 'TXT_KEY_PROMOTION_SILENT_HUNTER';

-- 空中掃蕩
UPDATE Language_en_US
SET Text = '可以執行[COLOR_POSITIVE_TEXT]空中掃蕩[ENDCOLOR]來清除目標單元格附近的攔截.'
WHERE Tag = 'TXT_KEY_PROMOTION_AIR_SWEEP_HELP';

UPDATE Language_en_US
SET Text = '加成 vs 直升機 (150)'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER';

UPDATE Language_en_US
SET Text = '國內焦點'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO';

UPDATE Language_en_US
SET Text = '不能在[COLOR_NEGATIVE_TEXT]海洋[ENDCOLOR]結束回合, 除非你已研究 [COLOR_CYAN]{TXT_KEY_TECH_COMPASS_TITLE}[ENDCOLOR].[NEWLINE]如果目的地是可見海岸,可以穿過可見海洋.'
WHERE Tag = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP';

-- Unwelcome Evangelist
UPDATE Language_en_US
SET Text = '沒有開放邊界也可以進入對手領土, 但如果在其境內結束回合, 會丟失 25% 原始宗教強度. 宗教強度到達 0 時, 單位會[COLOR_NEGATIVE_TEXT]被消除[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP';

-- Leadership
UPDATE Language_en_US
SET Text = '這個單位 2 單元格內的陸地單位 +15% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_GENERAL_HELP';

-- Naval Leadership
UPDATE Language_en_US
SET Text = '這個單位 2 單元格內的[COLOR_POSITIVE_TEXT]海軍單位[ENDCOLOR] +15% [ICON_STRENGTH]戰鬥力.[NEWLINE]可以使用 [COLOR_POSITIVE_TEXT]{TXT_KEY_MISSION_REPAIR_FLEET}[ENDCOLOR] 能力, 會消耗這個單位, 並且完全治療在這個單元格上或相鄰的所有[COLOR_POSITIVE_TEXT]海軍[ENDCOLOR]和[COLOR_POSITIVE_TEXT]海運單位[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP';

-- Withdraw Before Melee
UPDATE Language_en_US
SET Text = '如果此單位後方有空地,則從近戰攻擊中撤退,每回合一次.'
WHERE Tag = 'TXT_KEY_PROMOTION_WITHDRAW_BEFORE_MELEE_HELP';

UPDATE Language_en_US
SET Text = '團結'
WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE';

UPDATE Language_en_US
SET Text = '+10% [ICON_STRENGTH]戰鬥力.[NEWLINE]每個[COLOR_POSITIVE_TEXT]相鄰的己方陸地單位[ENDCOLOR] +15% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_DISCIPLINE_HELP';

-- Bonus vs Mounted (50)
UPDATE Language_en_US
SET Text = '+50% [ICON_STRENGTH]戰鬥力 VS [COLOR_POSITIVE_TEXT]騎乘單位[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升級時丟失.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP';

UPDATE Language_en_US
SET Text = '骷髏之鑰'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時 +150% [ICON_STRENGTH]戰鬥力.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升級時丟失.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_CITY_ASSUALT_HELP';

UPDATE Language_en_US
SET Text = '輕微攻城懲罰'
WHERE Tag = 'TXT_KEY_SMALL_PROMOTION_CITY_PENALTY';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_NEGATIVE_TEXT]城市[ENDCOLOR]時 -25% [ICON_STRENGTH]戰鬥力.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升級時丟失.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_SMALL_PROMOTION_CITY_PENALTY_HELP';

UPDATE Language_en_US
SET Text = '開闊地形加成 (30)'
WHERE Tag = 'TXT_KEY_PROMOTION_OPEN_TERRAIN';

-- Ranged Support Fire
UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]單位[ENDCOLOR]前, 執行一次 50% [ICON_STRENGTH]戰鬥力的[COLOR_POSITIVE_TEXT]遠程攻擊[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升級時丟失.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_RANGED_SUPPORT_FIRE_HELP';

UPDATE Language_en_US
SET Text = '堅韌'
WHERE Tag = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';

-- Combat Bonus in Forest/Jungle (33)
UPDATE Language_en_US
SET Text = '在[COLOR_POSITIVE_TEXT]森林[ENDCOLOR]和[COLOR_POSITIVE_TEXT]叢林[ENDCOLOR]上防守或攻擊單位時 +33% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_MOHAWK_HELP';

-- Combat Bonus in Forest/Jungle (33)
UPDATE Language_en_US
SET Text = '在[COLOR_POSITIVE_TEXT]森林[ENDCOLOR]和[COLOR_POSITIVE_TEXT]叢林[ENDCOLOR]上防守或攻擊單位時 +33% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_JAGUAR_HELP';

-- War Canoes
UPDATE Language_en_US
SET Text = '沿著河流移動有雙倍[ICON_MOVES]移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_WAR_CANOES_HELP';

UPDATE Language_en_US
SET Text = '遠征戰爭'
WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS';

UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]友好領土外[ENDCOLOR] +20% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_FOREIGN_LANDS_HELP';

UPDATE Language_en_US
SET Text = '更快治療'
WHERE Tag = 'TXT_KEY_PROMOTION_FASTER_HEAL';

UPDATE Language_en_US
SET Text = '槍法'
WHERE Tag = 'TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED';

UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]受傷單位[ENDCOLOR]時 +33% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP';

UPDATE Language_en_US
SET Text = '高地人'
WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY';

UPDATE Language_en_US
SET Text = '在[COLOR_POSITIVE_TEXT]雪原[ENDCOLOR], [COLOR_POSITIVE_TEXT]凍土[ENDCOLOR]和[COLOR_POSITIVE_TEXT]丘陵[ENDCOLOR]上有雙倍[ICON_MOVES]移動力.[NEWLINE]在無特征的[COLOR_POSITIVE_TEXT]雪原[ENDCOLOR], [COLOR_POSITIVE_TEXT]凍土[ENDCOLOR]和[COLOR_POSITIVE_TEXT]丘陵[ENDCOLOR]上防禦或進攻單位 +25% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_SKI_INFANTRY_HELP';

-- Haka War Dance
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]相鄰的敵人單位[ENDCOLOR] -15% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_HAKA_WAR_DANCE_HELP';

UPDATE Language_en_US
SET Text = 'Khaaaan!'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_GENERAL';

UPDATE Language_en_US
SET Text = '對在這個單位相鄰結束他們回合的敵人單位, 造成 10 傷害.[NEWLINE]這個傷害忽視傷害減免.'
WHERE Tag = 'TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP';

-- Quick Study
UPDATE Language_en_US
SET Text = '+50% 從戰鬥中獲得的經驗.'
WHERE Tag = 'TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP';

-- 貿易任務 Bonus
UPDATE Language_en_US
SET Text = '執行[COLOR_POSITIVE_TEXT]貿易任務[ENDCOLOR] +100% [ICON_GOLD]金幣.[NEWLINE]+2 [ICON_MOVES]海運移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_TRADE_MISSION_BONUS_HELP';

-- Heavy Charge
UPDATE Language_en_US
SET Text = '攻擊無法撤退的目標時 +50% [ICON_STRENGTH]戰鬥力. 如果目標所有修正之後的[ICON_STRENGTH]戰鬥力比這個單位還低, 目標會被強制後退(如果可能).'
WHERE Tag = 'TXT_KEY_PROMOTION_HEAVY_CHARGE_HELP';

-- Sapper
UPDATE Language_en_US
SET Text = '與敵人城市相鄰時, 單元格內的己方單位攻擊城市時, 獲得 +40% [ICON_STRENGTH]戰鬥力.[NEWLINE]如果在敵人城市 2 單元格內, 2 單元格內的己方單位攻擊城市時, 獲得 +20% [ICON_STRENGTH]戰鬥力.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]這些加成不會疊加.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SAPPER_HELP';

-- Golden Age from Victories
UPDATE Language_en_US
SET Text = '獲得被擊敗的敵人單位 100% [ICON_STRENGTH]戰鬥力的[ICON_GOLDEN_AGE]黃金時代點數.'
WHERE Tag = 'TXT_KEY_PROMOTION_GOLDEN_AGE_POINTS_HELP';

-- Homeland Guardian
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]友好領土內[ENDCOLOR] +25% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_HOMELAND_GUARDIAN_HELP';

-- Full Moon Striker
UPDATE Language_en_US
SET Text = '+1 [ICON_MOVES]移動力.[NEWLINE][COLOR_POSITIVE_TEXT]掠奪改良設施[ENDCOLOR]時, 獲得 200 [ICON_RESEARCH]科學.'
WHERE Tag = 'TXT_KEY_PROMOTION_MOON_STRIKER_HELP';

-- Mystic Blade
UPDATE Language_en_US
SET Text = '第一次戰鬥後,隨機獲得以下一個晉升:[NEWLINE][COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_INVULNERABIILITY}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_SNEAK_ATTACK}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_ENEMY_BLADE}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_AMBITION}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_EVIL_SPIRITS}[ENDCOLOR], [COLOR_POSITIVE_TEXT]{TXT_KEY_PROMOTION_RESTLESSNESS}[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_MYSTIC_BLADE_HELP';

-- Lightning Warfare
UPDATE Language_en_US
SET Text = '攻擊時 +15% [ICON_STRENGTH]戰鬥力.[NEWLINE]+1 [ICON_MOVES]移動力.[NEWLINE]忽視[COLOR_POSITIVE_TEXT]區域控制[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_LIGHTNING_WARFARE_HELP';

-- Exotic Cargo
UPDATE Language_en_US
SET Text = '鄰近外國領土時,可以 {TXT_KEY_MISSION_SELL_EXOTIC_GOODS} 以獲得[ICON_GOLD]金幣與 XP,數量依據與[ICON_CAPITAL]首都的距離而定,最多兩次.[NEWLINE]如果作為葡萄牙賣給城邦,就會在其領土上 [COLOR_POSITIVE_TEXT]自動建立[ENDCOLOR]一個商站.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升級時丟失.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_SELL_EXOTIC_GOODS_HELP';

-- City Plunder
UPDATE Language_en_US
SET Text = '攻擊[COLOR_POSITIVE_TEXT]城市[ENDCOLOR]時, 竊取等同於 100% 造成的傷害的[ICON_GOLD]金幣, 上限為 10x [ICON_STRENGTH]城市強度.'
WHERE Tag = 'TXT_KEY_PROMOTION_DOUBLE_PLUNDER_HELP';

-- Feared Elephant
UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]相鄰的敵人單位[ENDCOLOR] -10% [ICON_STRENGTH]戰鬥力.[NEWLINE][NEWLINE][COLOR_NEGATIVE_TEXT]升級時丟失.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP';

-- Enhanced Flank Attack
UPDATE Language_en_US
SET Text = '+10% [COLOR_POSITIVE_TEXT]側翼加成[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP';

-- Near Capital Bonus
UPDATE Language_en_US
SET Text = '你的[ICON_CAPITAL]首都 +30% [ICON_STRENGTH]戰鬥力; 每離你的[ICON_CAPITAL]首都一單元格, 加成下降 3%, 最大距離 9 單元格.'
WHERE Tag = 'TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP';

-- Great General Combat Bonus
UPDATE Language_en_US
SET Text = '大將軍所在這個單元格 +25% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_GENERAL_STACKING_HELP';

-- City Attack Only
UPDATE Language_en_US
SET Text = '無法攻擊[COLOR_NEGATIVE_TEXT]單位[ENDCOLOR].[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]升級時丟失.[ENDCOLOR]'
WHERE Tag = 'TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP';

-- Prize Ships
UPDATE Language_en_US
SET Text = '徵募被擊敗的敵人單位, 前提是其相鄰的單元格上(不計山嶽), 有一半或更多的己方單位正包圍它.[NEWLINE]佔領的單位開始時有 25% 的最大 HP 和 0 XP;並且可以立即移動(但不能攻擊).'
WHERE Tag = 'TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP';

-- Invulnerability
UPDATE Language_en_US
SET Text = ' -2 來自所有來源的傷害.[NEWLINE][COLOR_POSITIVE_TEXT]治療[ENDCOLOR]時 +20 HP.'
WHERE Tag = 'TXT_KEY_PROMOTION_INVULNERABIILITY_HELP';

-- Sneak Attack
UPDATE Language_en_US
SET Text = '+20% [COLOR_POSITIVE_TEXT]側翼加成[ENDCOLOR].[NEWLINE]忽視[COLOR_POSITIVE_TEXT]地形成本[ENDCOLOR]和[COLOR_POSITIVE_TEXT]區域控制[ENDCOLOR].'
WHERE Tag = 'TXT_KEY_PROMOTION_SNEAK_ATTACK_HELP';

UPDATE Language_en_US
SET Text = '決心'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION';

UPDATE Language_en_US
SET Text = '攻擊時 +30% [ICON_STRENGTH]戰鬥力.[NEWLINE]防御時 +5% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_AMBITION_HELP';

UPDATE Language_en_US
SET Text = '馬不停蹄'
WHERE Tag = 'TXT_KEY_PROMOTION_RESTLESSNESS';

UPDATE Language_en_US
SET Text = '+1 [ICON_WAR]攻擊.[NEWLINE]+1 [ICON_MOVES]移動力.'
WHERE Tag = 'TXT_KEY_PROMOTION_RESTLESSNESS_HELP';

UPDATE Language_en_US
SET Text = '就敵之刃'
WHERE Tag = 'TXT_KEY_PROMOTION_ENEMY_BLADE';

UPDATE Language_en_US
SET Text = '在[COLOR_POSITIVE_TEXT]敵人領土內[ENDCOLOR]開始回合時, 治療 10 HP.[NEWLINE]對在這個單位相鄰結束他們回合的敵人單位, 造成 10 傷害.[NEWLINE]這個傷害忽視傷害減免.'
WHERE Tag = 'TXT_KEY_PROMOTION_ENEMY_BLADE_HELP';

UPDATE Language_en_US
SET Text = '先祖庇護'
WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS';

UPDATE Language_en_US
SET Text = '攻擊時 +5% [ICON_STRENGTH]戰鬥力.[NEWLINE]防御時 +30% [ICON_STRENGTH]戰鬥力.'
WHERE Tag = 'TXT_KEY_PROMOTION_EVIL_SPIRITS_HELP';
